### ISSUE TITLE
Why only use the first patch? Thanks

### ISSUE THREAD

**Issue by junyongyou** [kamalkraj/Vision-Transformer#2]
I don't understand in line 158 of model.py:
`x = self.to_cls_token(x[:, 0])`
If the first dimension of x is batch, then the 2nd dimension 0 should be patch, as the dimension of x should be [batch, patch, feature]. Does it mean only the first patch is used? Could anybody help me on this? Thanks a lot.

**Comment by kamalkraj** [comment]
Hi @junyongyou,
Vision transformer is just like a BERT classifier. The classification information contains in the first token. You can find it in the paper also. 
![image](https://user-images.githubusercontent.com/17096858/97100421-6ab5eb00-16b9-11eb-9014-065d1c3c8e8a.png)
